export const mockPackages = [
  {
    id: "pkg1",
    trackingNumber: "TXM12345678",
    dispatchNumber: "DSP87654321",
    type: "Standard Package",
    weight: "5.2",
    shippedDate: "2024-04-28",
    estimatedDelivery: "2024-05-05",
    currentLocation: "Nairobi Distribution Center",
    nextStop: "Mombasa Hub",
    nextStopETA: "2024-05-02",
    finalDestination: "Mombasa",
    lastUpdated: "2024-05-01 08:30 AM",
    shippingAddress: {
      recipientName: "John Doe",
      streetAddress: "123 Ocean View Road",
      city: "Mombasa",
      state: "Coast",
      postalCode: "80100",
      country: "Kenya",
    },
    trackingHistory: [
      {
        status: "Package received",
        location: "Nairobi Warehouse",
        timestamp: "2024-04-28 09:15 AM",
      },
      {
        status: "In transit",
        location: "Nairobi Sorting Facility",
        timestamp: "2024-04-30 02:45 PM",
      },
      {
        status: "Arrived at facility",
        location: "Nairobi Distribution Center",
        timestamp: "2024-05-01 08:30 AM",
      },
    ],
  },
  {
    id: "pkg2",
    trackingNumber: "TXM98765432",
    dispatchNumber: "DSP12345678",
    type: "Express Package",
    weight: "2.8",
    shippedDate: "2024-04-30",
    estimatedDelivery: "2024-05-03",
    currentLocation: "Kampala Hub",
    nextStop: "Entebbe Distribution Center",
    nextStopETA: "2024-05-02",
    finalDestination: "Entebbe",
    lastUpdated: "2024-05-01 09:45 AM",
    shippingAddress: {
      recipientName: "Jane Smith",
      streetAddress: "456 Airport Road",
      city: "Entebbe",
      state: "Central Region",
      postalCode: "00256",
      country: "Uganda",
    },
    trackingHistory: [
      {
        status: "Package received",
        location: "Kampala Warehouse",
        timestamp: "2024-04-30 10:30 AM",
      },
      {
        status: "In transit",
        location: "Kampala Hub",
        timestamp: "2024-05-01 09:45 AM",
      },
    ],
  },
  {
    id: "pkg3",
    trackingNumber: "TXM45678901",
    dispatchNumber: "DSP10987654",
    type: "Heavy Freight",
    weight: "120.5",
    shippedDate: "2024-04-25",
    estimatedDelivery: "2024-05-10",
    currentLocation: "Mombasa Port",
    nextStop: "Nairobi Distribution",
    nextStopETA: "2024-05-04",
    finalDestination: "Nairobi",
    lastUpdated: "2024-04-30 11:20 AM",
    shippingAddress: {
      recipientName: "Acme Corporation",
      streetAddress: "789 Industrial Avenue",
      city: "Nairobi",
      state: "Nairobi County",
      postalCode: "00100",
      country: "Kenya",
    },
    trackingHistory: [
      {
        status: "Package received",
        location: "Mombasa Port",
        timestamp: "2024-04-25 08:00 AM",
      },
      {
        status: "Customs clearance",
        location: "Mombasa Customs",
        timestamp: "2024-04-28 03:15 PM",
      },
      {
        status: "In transit",
        location: "Mombasa Port",
        timestamp: "2024-04-30 11:20 AM",
      },
    ],
  },
  {
    id: "pkg4",
    trackingNumber: "TXM11223344",
    dispatchNumber: "DSP44332211",
    type: "Fragile Package",
    weight: "1.3",
    shippedDate: "2024-05-01",
    estimatedDelivery: "2024-05-04",
    currentLocation: "Dar es Salaam Sorting Facility",
    nextStop: "Arusha Distribution",
    nextStopETA: "2024-05-02",
    finalDestination: "Arusha",
    lastUpdated: "2024-05-01 10:15 AM",
    shippingAddress: {
      recipientName: "Robert Johnson",
      streetAddress: "321 Safari Road",
      city: "Arusha",
      state: "Arusha Region",
      postalCode: "23000",
      country: "Tanzania",
    },
    trackingHistory: [
      {
        status: "Package received",
        location: "Dar es Salaam Sorting Facility",
        timestamp: "2024-05-01 10:15 AM",
      },
    ],
  },
  {
    id: "pkg5",
    trackingNumber: "TXM55667788",
    dispatchNumber: "DSP88776655",
    type: "Refrigerated Goods",
    weight: "15.7",
    shippedDate: "2024-04-29",
    estimatedDelivery: "2024-05-06",
    currentLocation: "Kigali Cold Storage",
    nextStop: "Gisenyi Distribution",
    nextStopETA: "2024-05-03",
    finalDestination: "Gisenyi",
    lastUpdated: "2024-04-30 04:45 PM",
    shippingAddress: {
      recipientName: "Fresh Foods Ltd",
      streetAddress: "567 Lakeside Drive",
      city: "Gisenyi",
      state: "Western Province",
      postalCode: "00250",
      country: "Rwanda",
    },
    trackingHistory: [
      {
        status: "Package received",
        location: "Kigali Cold Storage",
        timestamp: "2024-04-29 11:30 AM",
      },
      {
        status: "In transit",
        location: "Kigali Cold Storage",
        timestamp: "2024-04-30 04:45 PM",
      },
    ],
  },
]
